name: CI/CD pipeline - test_despliegue
on:
    push:
        branches:
            - dev
            - test_despliegue
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Comienza el despliegue de mi aplicacion:"
      - run: echo "El usuario ${{ github.actor }} esta corriendo el CI/CD"

      # Use the latest version of checkout action
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or specify the version you need

      - run: echo "Comienzan a correr los comandos necesarios"
      
      - name: Change to frontend directory
        run: cd client

      - name: Install dependencies
        run: yarn install
        working-directory: ./client

      - name: Run tests
        run: yarn test
        working-directory: ./client